/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji'

export interface Config {
  auth: {
    users: UserAuthOperations
  }
  blocks: {}
  collections: {
    users: User
    media: Media
    pages: Page
    services: Service
    industries: Industry
    solutions: Solution
    'case-studies': CaseStudy
    blogs: Blog
    research: Research
    categories: Category
    tags: Tag
    authors: Author
    careers: Career
    departments: Department
    interviews: Interview
    'job-applications': JobApplication
    testimonials: Testimonial
    'team-members': TeamMember
    clients: Client
    faqs: Faq
    technologies: Technology
    'form-submissions': FormSubmission
    'contact-messages': ContactMessage
    'newsletter-subscribers': NewsletterSubscriber
    'newsletter-campaigns': NewsletterCampaign
    downloads: Download
    'activity-logs': ActivityLog
    notifications: Notification
    'analytics-events': AnalyticsEvent
    search: Search
    'payload-kv': PayloadKv
    'payload-locked-documents': PayloadLockedDocument
    'payload-preferences': PayloadPreference
    'payload-migrations': PayloadMigration
  }
  collectionsJoins: {}
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>
    media: MediaSelect<false> | MediaSelect<true>
    pages: PagesSelect<false> | PagesSelect<true>
    services: ServicesSelect<false> | ServicesSelect<true>
    industries: IndustriesSelect<false> | IndustriesSelect<true>
    solutions: SolutionsSelect<false> | SolutionsSelect<true>
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>
    blogs: BlogsSelect<false> | BlogsSelect<true>
    research: ResearchSelect<false> | ResearchSelect<true>
    categories: CategoriesSelect<false> | CategoriesSelect<true>
    tags: TagsSelect<false> | TagsSelect<true>
    authors: AuthorsSelect<false> | AuthorsSelect<true>
    careers: CareersSelect<false> | CareersSelect<true>
    departments: DepartmentsSelect<false> | DepartmentsSelect<true>
    interviews: InterviewsSelect<false> | InterviewsSelect<true>
    'job-applications': JobApplicationsSelect<false> | JobApplicationsSelect<true>
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>
    clients: ClientsSelect<false> | ClientsSelect<true>
    faqs: FaqsSelect<false> | FaqsSelect<true>
    technologies: TechnologiesSelect<false> | TechnologiesSelect<true>
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>
    'newsletter-campaigns': NewsletterCampaignsSelect<false> | NewsletterCampaignsSelect<true>
    downloads: DownloadsSelect<false> | DownloadsSelect<true>
    'activity-logs': ActivityLogsSelect<false> | ActivityLogsSelect<true>
    notifications: NotificationsSelect<false> | NotificationsSelect<true>
    'analytics-events': AnalyticsEventsSelect<false> | AnalyticsEventsSelect<true>
    search: SearchSelect<false> | SearchSelect<true>
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>
    'payload-locked-documents':
      PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>
  }
  db: {
    defaultIDType: string
  }
  fallbackLocale: null
  globals: {
    'site-settings': SiteSetting
    navigation: Navigation
    footer: Footer
    'contact-details': ContactDetail
    'office-locations': OfficeLocation
    'seo-defaults': SeoDefault
    'social-media': SocialMedia
    analytics: Analytics
    'announcement-bar': AnnouncementBar
    'cookie-banner': CookieBanner
  }
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>
    navigation: NavigationSelect<false> | NavigationSelect<true>
    footer: FooterSelect<false> | FooterSelect<true>
    'contact-details': ContactDetailsSelect<false> | ContactDetailsSelect<true>
    'office-locations': OfficeLocationsSelect<false> | OfficeLocationsSelect<true>
    'seo-defaults': SeoDefaultsSelect<false> | SeoDefaultsSelect<true>
    'social-media': SocialMediaSelect<false> | SocialMediaSelect<true>
    analytics: AnalyticsSelect<false> | AnalyticsSelect<true>
    'announcement-bar': AnnouncementBarSelect<false> | AnnouncementBarSelect<true>
    'cookie-banner': CookieBannerSelect<false> | CookieBannerSelect<true>
  }
  locale: null
  widgets: {
    collections: CollectionsWidget
  }
  user: User
  jobs: {
    tasks: unknown
    workflows: unknown
  }
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string
  roles: (
    | 'super-admin'
    | 'administrator'
    | 'editor'
    | 'content-manager'
    | 'marketing'
    | 'recruiter'
    | 'viewer'
  )[]
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  sessions?:
    | {
        id: string
        createdAt?: string | null
        expiresAt: string
      }[]
    | null
  password?: string | null
  collection: 'users'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string
  /**
   * Required for accessibility and SEO.
   */
  alt: string
  caption?: string | null
  /**
   * Freeform tags for Media Studio filters.
   */
  tags?:
    | {
        tag: string
        id?: string | null
      }[]
    | null
  folder?:
    | (
        | 'general'
        | 'hero'
        | 'blogs'
        | 'services'
        | 'industries'
        | 'team'
        | 'clients'
        | 'logos'
        | 'icons'
        | 'documents'
        | 'videos'
        | 'og'
      )
    | null
  updatedAt: string
  createdAt: string
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  focalX?: number | null
  focalY?: number | null
  sizes?: {
    thumbnail?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
    tablet?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
    desktop?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
    og?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
    avifDesktop?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    }
  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string
  title: string
  /**
   * URL slug. Auto-generated from title when empty.
   */
  slug: string
  layout: (
    | {
        eyebrow?: string | null
        heading: string
        subheading?: string | null
        ctaLabel?: string | null
        ctaHref?: string | null
        secondaryCtaLabel?: string | null
        secondaryCtaHref?: string | null
        image?: (string | null) | Media
        id?: string | null
        blockName?: string | null
        blockType: 'hero'
      }
    | {
        content: {
          root: {
            type: string
            children: {
              type: any
              version: number
              [k: string]: unknown
            }[]
            direction: ('ltr' | 'rtl') | null
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
            indent: number
            version: number
          }
          [k: string]: unknown
        }
        id?: string | null
        blockName?: string | null
        blockType: 'richText'
      }
    | {
        heading?: string | null
        stats?:
          | {
              label: string
              value: string
              suffix?: string | null
              id?: string | null
            }[]
          | null
        id?: string | null
        blockName?: string | null
        blockType: 'statistics'
      }
    | {
        heading: string
        stats?:
          | {
              label: string
              value: string
              id?: string | null
            }[]
          | null
        id?: string | null
        blockName?: string | null
        blockType: 'statsRow'
      }
    | {
        heading: string
        subheading?: string | null
        id?: string | null
        blockName?: string | null
        blockType: 'servicesGrid'
      }
    | {
        heading: string
        subheading?: string | null
        id?: string | null
        blockName?: string | null
        blockType: 'technologyGrid'
      }
    | {
        heading: string
        subheading?: string | null
        items?:
          | {
              date?: string | null
              title: string
              description?: string | null
              id?: string | null
            }[]
          | null
        id?: string | null
        blockName?: string | null
        blockType: 'timeline'
      }
    | {
        heading: string
        id?: string | null
        blockName?: string | null
        blockType: 'testimonials'
      }
    | {
        heading: string
        group?: string | null
        id?: string | null
        blockName?: string | null
        blockType: 'faqAccordion'
      }
    | {
        heading: string
        subheading?: string | null
        ctaLabel?: string | null
        ctaHref?: string | null
        id?: string | null
        blockName?: string | null
        blockType: 'ctaBand'
      }
    | {
        heading: string
        subheading?: string | null
        cta?: {
          label?: string | null
          href?: string | null
          style?: ('primary' | 'secondary' | 'ghost') | null
          openInNewTab?: boolean | null
        }
        id?: string | null
        blockName?: string | null
        blockType: 'contactCta'
      }
    | {
        heading?: string | null
        subheading?: string | null
        images?:
          | {
              image: string | Media
              caption?: string | null
              alt?: string | null
              id?: string | null
            }[]
          | null
        id?: string | null
        blockName?: string | null
        blockType: 'imageGallery'
      }
    | {
        heading: string
        subheading?: string | null
        /**
         * Upload MP4/WebM or paste an embed URL below.
         */
        video?: (string | null) | Media
        embedUrl?: string | null
        poster?: (string | null) | Media
        id?: string | null
        blockName?: string | null
        blockType: 'videoSection'
      }
    | {
        heading: string
        subheading?: string | null
        id?: string | null
        blockName?: string | null
        blockType: 'latestBlogs'
      }
    | {
        heading: string
        subheading?: string | null
        cta?: {
          label?: string | null
          href?: string | null
          style?: ('primary' | 'secondary' | 'ghost') | null
          openInNewTab?: boolean | null
        }
        id?: string | null
        blockName?: string | null
        blockType: 'careerBanner'
      }
    | {
        heading: string
        subheading?: string | null
        id?: string | null
        blockName?: string | null
        blockType: 'newsletter'
      }
    | {
        heading: string
        body: string
        cta?: {
          label?: string | null
          href?: string | null
          style?: ('primary' | 'secondary' | 'ghost') | null
          openInNewTab?: boolean | null
        }
        id?: string | null
        blockName?: string | null
        blockType: 'aboutPreview'
      }
    | {
        heading: string
        subheading?: string | null
        id?: string | null
        blockName?: string | null
        blockType: 'industriesStrip'
      }
    | {
        heading: string
        subheading?: string | null
        items?:
          | {
              title: string
              description: string
              id?: string | null
            }[]
          | null
        id?: string | null
        blockName?: string | null
        blockType: 'whyChooseUs'
      }
    | {
        heading: string
        id?: string | null
        blockName?: string | null
        blockType: 'caseStudyFeature'
      }
    | {
        heading: string
        steps?:
          | {
              title: string
              description: string
              id?: string | null
            }[]
          | null
        id?: string | null
        blockName?: string | null
        blockType: 'processSteps'
      }
    | {
        heading: string
        id?: string | null
        blockName?: string | null
        blockType: 'teamGrid'
      }
    | {
        heading: string
        id?: string | null
        blockName?: string | null
        blockType: 'clientLogos'
      }
    | {
        heading: string
        body?: {
          root: {
            type: string
            children: {
              type: any
              version: number
              [k: string]: unknown
            }[]
            direction: ('ltr' | 'rtl') | null
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
            indent: number
            version: number
          }
          [k: string]: unknown
        } | null
        image?: (string | null) | Media
        reverse?: boolean | null
        id?: string | null
        blockName?: string | null
        blockType: 'featureSplit'
      }
    | {
        heading: string
        missionTitle?: string | null
        missionBody: string
        visionTitle?: string | null
        visionBody: string
        id?: string | null
        blockName?: string | null
        blockType: 'missionVision'
      }
    | {
        heading: string
        subheading?: string | null
        values?:
          | {
              title: string
              description: string
              id?: string | null
            }[]
          | null
        id?: string | null
        blockName?: string | null
        blockType: 'valuesGrid'
      }
    | {
        brand?: string | null
        eyebrow?: string | null
        heading: string
        subheading?: string | null
        ctaLabel?: string | null
        ctaHref?: string | null
        secondaryCtaLabel?: string | null
        secondaryCtaHref?: string | null
        id?: string | null
        blockName?: string | null
        blockType: 'storyHero'
      }
    | {
        eyebrow?: string | null
        heading: string
        items?:
          | {
              title: string
              body?: string | null
              id?: string | null
            }[]
          | null
        id?: string | null
        blockName?: string | null
        blockType: 'storyChallenge'
      }
    | {
        eyebrow?: string | null
        heading: string
        chapters?:
          | {
              title: string
              body: string
              id?: string | null
            }[]
          | null
        id?: string | null
        blockName?: string | null
        blockType: 'storySolution'
      }
    | {
        eyebrow?: string | null
        heading: string
        subheading?: string | null
        id?: string | null
        blockName?: string | null
        blockType: 'storyCapabilities'
      }
    | {
        eyebrow?: string | null
        heading: string
        subheading?: string | null
        id?: string | null
        blockName?: string | null
        blockType: 'storyTechOrbit'
      }
    | {
        eyebrow?: string | null
        heading: string
        stats?:
          | {
              label: string
              value: string
              suffix?: string | null
              id?: string | null
            }[]
          | null
        id?: string | null
        blockName?: string | null
        blockType: 'storyProof'
      }
    | {
        eyebrow?: string | null
        heading: string
        id?: string | null
        blockName?: string | null
        blockType: 'storyCases'
      }
    | {
        eyebrow?: string | null
        heading: string
        steps?:
          | {
              title: string
              description: string
              id?: string | null
            }[]
          | null
        id?: string | null
        blockName?: string | null
        blockType: 'storyProcess'
      }
    | {
        eyebrow?: string | null
        heading: string
        id?: string | null
        blockName?: string | null
        blockType: 'storyPresence'
      }
    | {
        heading: string
        subheading?: string | null
        ctaLabel?: string | null
        ctaHref?: string | null
        id?: string | null
        blockName?: string | null
        blockType: 'storyCta'
      }
  )[]
  meta?: {
    title?: string | null
    description?: string | null
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media
  }
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string
  title: string
  /**
   * URL slug. Auto-generated from title when empty.
   */
  slug: string
  summary: string
  /**
   * Lucide icon name (e.g. cloud, code, shield)
   */
  icon?: string | null
  heroImage?: (string | null) | Media
  challenges?: string | null
  body: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  }
  benefits?:
    | {
        title: string
        description: string
        id?: string | null
      }[]
    | null
  process?:
    | {
        title: string
        description: string
        id?: string | null
      }[]
    | null
  /**
   * Engineering stack for this capability (not clinical standards).
   */
  technologies?: (string | Technology)[] | null
  /**
   * Business problems this capability helps solve.
   */
  relatedSolutions?: (string | Solution)[] | null
  relatedIndustries?: (string | Industry)[] | null
  relatedCaseStudies?: (string | CaseStudy)[] | null
  relatedResearch?: (string | Research)[] | null
  relatedInsights?: (string | Blog)[] | null
  relatedFaqs?: (string | Faq)[] | null
  /**
   * Show in featured lists and homepage modules.
   */
  featured?: boolean | null
  /**
   * Lower numbers appear first.
   */
  order?: number | null
  meta?: {
    title?: string | null
    description?: string | null
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media
  }
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies".
 */
export interface Technology {
  id: string
  title: string
  /**
   * URL slug. Auto-generated from title when empty.
   */
  slug: string
  /**
   * Engineering stack categories only. Clinical standards (SAS/SDTM/CDISC) belong in Healthcare service capability content—not this catalog.
   */
  category:
    | 'frontend'
    | 'backend'
    | 'cloud'
    | 'devops'
    | 'ai'
    | 'database'
    | 'data'
    | 'bi'
    | 'cms'
    | 'other'
  logo?: (string | null) | Media
  description?: string | null
  /**
   * Show in featured lists and homepage modules.
   */
  featured?: boolean | null
  /**
   * Lower numbers appear first.
   */
  order?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions".
 */
export interface Solution {
  id: string
  title: string
  /**
   * URL slug. Auto-generated from title when empty.
   */
  slug: string
  summary: string
  body: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  }
  businessChallenges?:
    | {
        title: string
        description?: string | null
        id?: string | null
      }[]
    | null
  useCases?:
    | {
        title: string
        description?: string | null
        id?: string | null
      }[]
    | null
  outcomes?:
    | {
        title: string
        description?: string | null
        id?: string | null
      }[]
    | null
  whoIsThisFor?: string | null
  relatedServices?: (string | Service)[] | null
  relatedIndustries?: (string | Industry)[] | null
  /**
   * Technologies specific to this solution—use the canonical Solution → Technology matrix (not inherited from services).
   */
  technologies?: (string | Technology)[] | null
  relatedCaseStudies?: (string | CaseStudy)[] | null
  relatedResearch?: (string | Research)[] | null
  relatedInsights?: (string | Blog)[] | null
  relatedFaqs?: (string | Faq)[] | null
  /**
   * Show in featured lists and homepage modules.
   */
  featured?: boolean | null
  /**
   * Lower numbers appear first.
   */
  order?: number | null
  meta?: {
    title?: string | null
    description?: string | null
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media
  }
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: string
  title: string
  /**
   * URL slug. Auto-generated from title when empty.
   */
  slug: string
  summary: string
  heroImage?: (string | null) | Media
  /**
   * Prefer structured Problems below. Kept for compatibility.
   */
  challenges?: string | null
  problems?:
    | {
        title: string
        description: string
        id?: string | null
      }[]
    | null
  /**
   * Prefer Related Solutions relationship below.
   */
  solutions?:
    | {
        title: string
        description: string
        id?: string | null
      }[]
    | null
  approach?: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  } | null
  relatedServices?: (string | Service)[] | null
  relatedSolutions?: (string | Solution)[] | null
  relatedTechnologies?: (string | Technology)[] | null
  relatedCaseStudies?: (string | CaseStudy)[] | null
  relatedResearch?: (string | Research)[] | null
  relatedInsights?: (string | Blog)[] | null
  /**
   * Controls nav prominence. Tier 3 stays out of primary mega until content-ready.
   */
  tier?: ('1' | '2' | '3') | null
  /**
   * Show in featured lists and homepage modules.
   */
  featured?: boolean | null
  /**
   * Lower numbers appear first.
   */
  order?: number | null
  meta?: {
    title?: string | null
    description?: string | null
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media
  }
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: string
  title: string
  /**
   * URL slug. Auto-generated from title when empty.
   */
  slug: string
  clientRef?: (string | null) | Client
  /**
   * Display name. Prefer Client relationship when available.
   */
  client: string
  industry?: (string | null) | Industry
  challenge: string
  outcome: string
  metrics?:
    | {
        label: string
        value: string
        id?: string | null
      }[]
    | null
  services?: (string | Service)[] | null
  relatedSolutions?: (string | Solution)[] | null
  technologies?: (string | Technology)[] | null
  featuredImage?: (string | null) | Media
  meta?: {
    title?: string | null
    description?: string | null
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media
  }
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: string
  name: string
  logo: string | Media
  url?: string | null
  featured?: boolean | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research".
 */
export interface Research {
  id: string
  title: string
  /**
   * URL slug. Auto-generated from title when empty.
   */
  slug: string
  excerpt: string
  content: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  }
  cover?: (string | null) | Media
  authors?: (string | Author)[] | null
  relatedServices?: (string | Service)[] | null
  relatedSolutions?: (string | Solution)[] | null
  relatedIndustries?: (string | Industry)[] | null
  /**
   * Show in featured lists and homepage modules.
   */
  featured?: boolean | null
  /**
   * Public publish timestamp.
   */
  publishedAt?: string | null
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: string
  name: string
  role?: string | null
  bio?: string | null
  avatar?: (string | null) | Media
  linkedIn?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: string
  title: string
  /**
   * URL slug. Auto-generated from title when empty.
   */
  slug: string
  /**
   * Used by Insights hub filters.
   */
  insightType?: ('blog' | 'white-paper' | 'news' | 'resource') | null
  excerpt: string
  content: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  }
  cover?: (string | null) | Media
  author?: (string | null) | Author
  categories?: (string | Category)[] | null
  tags?: (string | Tag)[] | null
  relatedServices?: (string | Service)[] | null
  relatedSolutions?: (string | Solution)[] | null
  relatedIndustries?: (string | Industry)[] | null
  /**
   * Minutes. Auto-estimated on save if empty.
   */
  readingTime?: number | null
  /**
   * Show in featured lists and homepage modules.
   */
  featured?: boolean | null
  /**
   * Public publish timestamp.
   */
  publishedAt?: string | null
  meta?: {
    title?: string | null
    description?: string | null
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media
  }
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string
  title: string
  /**
   * URL slug. Auto-generated from title when empty.
   */
  slug: string
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string
  title: string
  /**
   * URL slug. Auto-generated from title when empty.
   */
  slug: string
  description?: string | null
  /**
   * Lower numbers appear first.
   */
  order?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string
  question: string
  answer: string
  /**
   * Optional grouping label (e.g. Services, Careers)
   */
  group?: string | null
  relatedServices?: (string | Service)[] | null
  relatedPages?: (string | Page)[] | null
  /**
   * Lower numbers appear first.
   */
  order?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers".
 */
export interface Career {
  id: string
  title: string
  /**
   * URL slug. Auto-generated from title when empty.
   */
  slug: string
  departmentRef?: (string | null) | Department
  /**
   * Prefer Department relationship. Kept for compatibility.
   */
  department?: string | null
  /**
   * Display location (e.g. Hyderabad · Hybrid)
   */
  office?: string | null
  location: string
  type: 'full-time' | 'part-time' | 'contract' | 'internship'
  workMode?: ('onsite' | 'hybrid' | 'remote') | null
  /**
   * e.g. 2–5 Years
   */
  experienceRequired?: string | null
  openings?: number | null
  postedAt?: string | null
  applicationDeadline?: string | null
  aboutRole?: string | null
  description: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  }
  responsibilities?:
    | {
        item: string
        id?: string | null
      }[]
    | null
  requiredSkills?:
    | {
        item: string
        id?: string | null
      }[]
    | null
  preferredSkills?:
    | {
        item: string
        id?: string | null
      }[]
    | null
  qualifications?: string | null
  benefits?:
    | {
        item: string
        id?: string | null
      }[]
    | null
  requirements: {
    root: {
      type: string
      children: {
        type: any
        version: number
        [k: string]: unknown
      }[]
      direction: ('ltr' | 'rtl') | null
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | ''
      indent: number
      version: number
    }
    [k: string]: unknown
  }
  relatedServices?: (string | Service)[] | null
  relatedSolutions?: (string | Solution)[] | null
  relatedIndustries?: (string | Industry)[] | null
  active?: boolean | null
  meta?: {
    title?: string | null
    description?: string | null
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media
  }
  updatedAt: string
  createdAt: string
  _status?: ('draft' | 'published') | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments".
 */
export interface Department {
  id: string
  title: string
  /**
   * URL slug. Auto-generated from title when empty.
   */
  slug: string
  description?: string | null
  /**
   * Lower numbers appear first.
   */
  order?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "interviews".
 */
export interface Interview {
  id: string
  /**
   * e.g. Technical screen — Jane Doe
   */
  title: string
  application: string | JobApplication
  job?: (string | null) | Career
  interviewers?: (string | User)[] | null
  scheduledAt: string
  mode: 'video' | 'onsite' | 'phone'
  meetingLink?: string | null
  outcome?: ('scheduled' | 'completed' | 'no-show' | 'cancelled' | 'advance' | 'reject') | null
  notes?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications".
 */
export interface JobApplication {
  id: string
  applicationId?: string | null
  career: string | Career
  /**
   * Display name (auto from first/last).
   */
  name: string
  firstName?: string | null
  lastName?: string | null
  email: string
  phone?: string | null
  country?: string | null
  city?: string | null
  linkedin?: string | null
  portfolio?: string | null
  currentCompany?: string | null
  currentDesignation?: string | null
  totalExperience?: string | null
  relevantExperience?: string | null
  currentSalary?: string | null
  expectedSalary?: string | null
  noticePeriod?: string | null
  workAuthorization?: string | null
  education?: {
    highestQualification?: string | null
    university?: string | null
    graduationYear?: string | null
  }
  skills?:
    | {
        item: string
        id?: string | null
      }[]
    | null
  resume: string | Media
  coverLetter?: string | null
  whyJoin?: string | null
  willingToRelocate?: ('yes' | 'no' | 'maybe') | null
  earliestJoinDate?: string | null
  healthcareExperience?: ('yes' | 'no') | null
  consent: boolean
  status:
    | 'new'
    | 'under-review'
    | 'shortlisted'
    | 'interview-scheduled'
    | 'technical-assessment'
    | 'final-interview'
    | 'offered'
    | 'hired'
    | 'rejected'
    | 'withdrawn'
  recruiterNotes?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string
  quote: string
  authorName: string
  authorRole?: string | null
  company?: string | null
  logo?: (string | null) | Media
  featured?: boolean | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: string
  name: string
  role: string
  department?: (string | null) | Department
  bio?: string | null
  photo?: (string | null) | Media
  /**
   * Lower numbers appear first.
   */
  order?: number | null
  linkedIn?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string
  type: 'contact' | 'newsletter'
  data:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  status: 'new' | 'reviewed' | 'archived'
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: string
  name: string
  company?: string | null
  email: string
  phone?: string | null
  subject?: string | null
  message: string
  intent?:
    | (
        | 'business'
        | 'data-science'
        | 'it-consulting'
        | 'digital-transformation'
        | 'data-engineering'
        | 'healthcare'
        | 'research'
        | 'partnership'
        | 'career'
        | 'general'
        | 'project'
      )
    | null
  jobTitle?: string | null
  country?: string | null
  status: 'new' | 'assigned' | 'meeting' | 'proposal' | 'won' | 'lost' | 'in-progress' | 'closed'
  assignee?: (string | null) | User
  meetingAt?: string | null
  nextFollowUp?: string | null
  /**
   * Optional estimated deal value
   */
  dealValue?: number | null
  activityNotes?:
    | {
        note: string
        at?: string | null
        id?: string | null
      }[]
    | null
  /**
   * Internal summary notes
   */
  notes?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: string
  email: string
  status: 'active' | 'unsubscribed'
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-campaigns".
 */
export interface NewsletterCampaign {
  id: string
  title: string
  subject: string
  sentAt?: string | null
  audienceFilter?: ('active' | 'all' | 'unsubscribed') | null
  notes?: string | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "downloads".
 */
export interface Download {
  id: string
  title: string
  /**
   * URL slug. Auto-generated from title when empty.
   */
  slug: string
  description?: string | null
  file: string | Media
  relatedBlog?: (string | null) | Blog
  relatedResearch?: (string | null) | Research
  /**
   * Require email capture before download (handled on the site).
   */
  gated?: boolean | null
  downloadCount?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-logs".
 */
export interface ActivityLog {
  id: string
  summary: string
  action: 'created' | 'updated' | 'published' | 'deleted' | 'status-change' | 'upload'
  /**
   * Source collection slug (avoids Mongoose reserved key “collection”).
   */
  collectionSlug: string
  documentId?: string | null
  actor?: (string | null) | User
  meta?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: string
  title: string
  body?: string | null
  type: 'lead' | 'application' | 'interview' | 'publish' | 'media' | 'info'
  href?: string | null
  user: string | User
  read?: boolean | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-events".
 */
export interface AnalyticsEvent {
  id: string
  type: 'pageview' | 'lead' | 'application' | 'download' | 'newsletter'
  path?: string | null
  referrer?: string | null
  meta?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string
  title?: string | null
  priority?: number | null
  doc:
    | {
        relationTo: 'pages'
        value: string | Page
      }
    | {
        relationTo: 'services'
        value: string | Service
      }
    | {
        relationTo: 'industries'
        value: string | Industry
      }
    | {
        relationTo: 'solutions'
        value: string | Solution
      }
    | {
        relationTo: 'blogs'
        value: string | Blog
      }
    | {
        relationTo: 'careers'
        value: string | Career
      }
    | {
        relationTo: 'case-studies'
        value: string | CaseStudy
      }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string
  key: string
  data:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string
  document?:
    | ({
        relationTo: 'users'
        value: string | User
      } | null)
    | ({
        relationTo: 'media'
        value: string | Media
      } | null)
    | ({
        relationTo: 'pages'
        value: string | Page
      } | null)
    | ({
        relationTo: 'services'
        value: string | Service
      } | null)
    | ({
        relationTo: 'industries'
        value: string | Industry
      } | null)
    | ({
        relationTo: 'solutions'
        value: string | Solution
      } | null)
    | ({
        relationTo: 'case-studies'
        value: string | CaseStudy
      } | null)
    | ({
        relationTo: 'blogs'
        value: string | Blog
      } | null)
    | ({
        relationTo: 'research'
        value: string | Research
      } | null)
    | ({
        relationTo: 'categories'
        value: string | Category
      } | null)
    | ({
        relationTo: 'tags'
        value: string | Tag
      } | null)
    | ({
        relationTo: 'authors'
        value: string | Author
      } | null)
    | ({
        relationTo: 'careers'
        value: string | Career
      } | null)
    | ({
        relationTo: 'departments'
        value: string | Department
      } | null)
    | ({
        relationTo: 'interviews'
        value: string | Interview
      } | null)
    | ({
        relationTo: 'job-applications'
        value: string | JobApplication
      } | null)
    | ({
        relationTo: 'testimonials'
        value: string | Testimonial
      } | null)
    | ({
        relationTo: 'team-members'
        value: string | TeamMember
      } | null)
    | ({
        relationTo: 'clients'
        value: string | Client
      } | null)
    | ({
        relationTo: 'faqs'
        value: string | Faq
      } | null)
    | ({
        relationTo: 'technologies'
        value: string | Technology
      } | null)
    | ({
        relationTo: 'form-submissions'
        value: string | FormSubmission
      } | null)
    | ({
        relationTo: 'contact-messages'
        value: string | ContactMessage
      } | null)
    | ({
        relationTo: 'newsletter-subscribers'
        value: string | NewsletterSubscriber
      } | null)
    | ({
        relationTo: 'newsletter-campaigns'
        value: string | NewsletterCampaign
      } | null)
    | ({
        relationTo: 'downloads'
        value: string | Download
      } | null)
    | ({
        relationTo: 'activity-logs'
        value: string | ActivityLog
      } | null)
    | ({
        relationTo: 'notifications'
        value: string | Notification
      } | null)
    | ({
        relationTo: 'analytics-events'
        value: string | AnalyticsEvent
      } | null)
    | ({
        relationTo: 'search'
        value: string | Search
      } | null)
  globalSlug?: string | null
  user: {
    relationTo: 'users'
    value: string | User
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string
  user: {
    relationTo: 'users'
    value: string | User
  }
  key?: string | null
  value?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string
  name?: string | null
  batch?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T
  updatedAt?: T
  createdAt?: T
  email?: T
  resetPasswordToken?: T
  resetPasswordExpiration?: T
  salt?: T
  hash?: T
  loginAttempts?: T
  lockUntil?: T
  sessions?:
    | T
    | {
        id?: T
        createdAt?: T
        expiresAt?: T
      }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T
  caption?: T
  tags?:
    | T
    | {
        tag?: T
        id?: T
      }
  folder?: T
  updatedAt?: T
  createdAt?: T
  url?: T
  thumbnailURL?: T
  filename?: T
  mimeType?: T
  filesize?: T
  width?: T
  height?: T
  focalX?: T
  focalY?: T
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T
              width?: T
              height?: T
              mimeType?: T
              filesize?: T
              filename?: T
            }
        tablet?:
          | T
          | {
              url?: T
              width?: T
              height?: T
              mimeType?: T
              filesize?: T
              filename?: T
            }
        desktop?:
          | T
          | {
              url?: T
              width?: T
              height?: T
              mimeType?: T
              filesize?: T
              filename?: T
            }
        og?:
          | T
          | {
              url?: T
              width?: T
              height?: T
              mimeType?: T
              filesize?: T
              filename?: T
            }
        avifDesktop?:
          | T
          | {
              url?: T
              width?: T
              height?: T
              mimeType?: T
              filesize?: T
              filename?: T
            }
      }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T
  slug?: T
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T
              heading?: T
              subheading?: T
              ctaLabel?: T
              ctaHref?: T
              secondaryCtaLabel?: T
              secondaryCtaHref?: T
              image?: T
              id?: T
              blockName?: T
            }
        richText?:
          | T
          | {
              content?: T
              id?: T
              blockName?: T
            }
        statistics?:
          | T
          | {
              heading?: T
              stats?:
                | T
                | {
                    label?: T
                    value?: T
                    suffix?: T
                    id?: T
                  }
              id?: T
              blockName?: T
            }
        statsRow?:
          | T
          | {
              heading?: T
              stats?:
                | T
                | {
                    label?: T
                    value?: T
                    id?: T
                  }
              id?: T
              blockName?: T
            }
        servicesGrid?:
          | T
          | {
              heading?: T
              subheading?: T
              id?: T
              blockName?: T
            }
        technologyGrid?:
          | T
          | {
              heading?: T
              subheading?: T
              id?: T
              blockName?: T
            }
        timeline?:
          | T
          | {
              heading?: T
              subheading?: T
              items?:
                | T
                | {
                    date?: T
                    title?: T
                    description?: T
                    id?: T
                  }
              id?: T
              blockName?: T
            }
        testimonials?:
          | T
          | {
              heading?: T
              id?: T
              blockName?: T
            }
        faqAccordion?:
          | T
          | {
              heading?: T
              group?: T
              id?: T
              blockName?: T
            }
        ctaBand?:
          | T
          | {
              heading?: T
              subheading?: T
              ctaLabel?: T
              ctaHref?: T
              id?: T
              blockName?: T
            }
        contactCta?:
          | T
          | {
              heading?: T
              subheading?: T
              cta?:
                | T
                | {
                    label?: T
                    href?: T
                    style?: T
                    openInNewTab?: T
                  }
              id?: T
              blockName?: T
            }
        imageGallery?:
          | T
          | {
              heading?: T
              subheading?: T
              images?:
                | T
                | {
                    image?: T
                    caption?: T
                    alt?: T
                    id?: T
                  }
              id?: T
              blockName?: T
            }
        videoSection?:
          | T
          | {
              heading?: T
              subheading?: T
              video?: T
              embedUrl?: T
              poster?: T
              id?: T
              blockName?: T
            }
        latestBlogs?:
          | T
          | {
              heading?: T
              subheading?: T
              id?: T
              blockName?: T
            }
        careerBanner?:
          | T
          | {
              heading?: T
              subheading?: T
              cta?:
                | T
                | {
                    label?: T
                    href?: T
                    style?: T
                    openInNewTab?: T
                  }
              id?: T
              blockName?: T
            }
        newsletter?:
          | T
          | {
              heading?: T
              subheading?: T
              id?: T
              blockName?: T
            }
        aboutPreview?:
          | T
          | {
              heading?: T
              body?: T
              cta?:
                | T
                | {
                    label?: T
                    href?: T
                    style?: T
                    openInNewTab?: T
                  }
              id?: T
              blockName?: T
            }
        industriesStrip?:
          | T
          | {
              heading?: T
              subheading?: T
              id?: T
              blockName?: T
            }
        whyChooseUs?:
          | T
          | {
              heading?: T
              subheading?: T
              items?:
                | T
                | {
                    title?: T
                    description?: T
                    id?: T
                  }
              id?: T
              blockName?: T
            }
        caseStudyFeature?:
          | T
          | {
              heading?: T
              id?: T
              blockName?: T
            }
        processSteps?:
          | T
          | {
              heading?: T
              steps?:
                | T
                | {
                    title?: T
                    description?: T
                    id?: T
                  }
              id?: T
              blockName?: T
            }
        teamGrid?:
          | T
          | {
              heading?: T
              id?: T
              blockName?: T
            }
        clientLogos?:
          | T
          | {
              heading?: T
              id?: T
              blockName?: T
            }
        featureSplit?:
          | T
          | {
              heading?: T
              body?: T
              image?: T
              reverse?: T
              id?: T
              blockName?: T
            }
        missionVision?:
          | T
          | {
              heading?: T
              missionTitle?: T
              missionBody?: T
              visionTitle?: T
              visionBody?: T
              id?: T
              blockName?: T
            }
        valuesGrid?:
          | T
          | {
              heading?: T
              subheading?: T
              values?:
                | T
                | {
                    title?: T
                    description?: T
                    id?: T
                  }
              id?: T
              blockName?: T
            }
        storyHero?:
          | T
          | {
              brand?: T
              eyebrow?: T
              heading?: T
              subheading?: T
              ctaLabel?: T
              ctaHref?: T
              secondaryCtaLabel?: T
              secondaryCtaHref?: T
              id?: T
              blockName?: T
            }
        storyChallenge?:
          | T
          | {
              eyebrow?: T
              heading?: T
              items?:
                | T
                | {
                    title?: T
                    body?: T
                    id?: T
                  }
              id?: T
              blockName?: T
            }
        storySolution?:
          | T
          | {
              eyebrow?: T
              heading?: T
              chapters?:
                | T
                | {
                    title?: T
                    body?: T
                    id?: T
                  }
              id?: T
              blockName?: T
            }
        storyCapabilities?:
          | T
          | {
              eyebrow?: T
              heading?: T
              subheading?: T
              id?: T
              blockName?: T
            }
        storyTechOrbit?:
          | T
          | {
              eyebrow?: T
              heading?: T
              subheading?: T
              id?: T
              blockName?: T
            }
        storyProof?:
          | T
          | {
              eyebrow?: T
              heading?: T
              stats?:
                | T
                | {
                    label?: T
                    value?: T
                    suffix?: T
                    id?: T
                  }
              id?: T
              blockName?: T
            }
        storyCases?:
          | T
          | {
              eyebrow?: T
              heading?: T
              id?: T
              blockName?: T
            }
        storyProcess?:
          | T
          | {
              eyebrow?: T
              heading?: T
              steps?:
                | T
                | {
                    title?: T
                    description?: T
                    id?: T
                  }
              id?: T
              blockName?: T
            }
        storyPresence?:
          | T
          | {
              eyebrow?: T
              heading?: T
              id?: T
              blockName?: T
            }
        storyCta?:
          | T
          | {
              heading?: T
              subheading?: T
              ctaLabel?: T
              ctaHref?: T
              id?: T
              blockName?: T
            }
      }
  meta?:
    | T
    | {
        title?: T
        description?: T
        image?: T
      }
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T
  slug?: T
  summary?: T
  icon?: T
  heroImage?: T
  challenges?: T
  body?: T
  benefits?:
    | T
    | {
        title?: T
        description?: T
        id?: T
      }
  process?:
    | T
    | {
        title?: T
        description?: T
        id?: T
      }
  technologies?: T
  relatedSolutions?: T
  relatedIndustries?: T
  relatedCaseStudies?: T
  relatedResearch?: T
  relatedInsights?: T
  relatedFaqs?: T
  featured?: T
  order?: T
  meta?:
    | T
    | {
        title?: T
        description?: T
        image?: T
      }
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  title?: T
  slug?: T
  summary?: T
  heroImage?: T
  challenges?: T
  problems?:
    | T
    | {
        title?: T
        description?: T
        id?: T
      }
  solutions?:
    | T
    | {
        title?: T
        description?: T
        id?: T
      }
  approach?: T
  relatedServices?: T
  relatedSolutions?: T
  relatedTechnologies?: T
  relatedCaseStudies?: T
  relatedResearch?: T
  relatedInsights?: T
  tier?: T
  featured?: T
  order?: T
  meta?:
    | T
    | {
        title?: T
        description?: T
        image?: T
      }
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions_select".
 */
export interface SolutionsSelect<T extends boolean = true> {
  title?: T
  slug?: T
  summary?: T
  body?: T
  businessChallenges?:
    | T
    | {
        title?: T
        description?: T
        id?: T
      }
  useCases?:
    | T
    | {
        title?: T
        description?: T
        id?: T
      }
  outcomes?:
    | T
    | {
        title?: T
        description?: T
        id?: T
      }
  whoIsThisFor?: T
  relatedServices?: T
  relatedIndustries?: T
  technologies?: T
  relatedCaseStudies?: T
  relatedResearch?: T
  relatedInsights?: T
  relatedFaqs?: T
  featured?: T
  order?: T
  meta?:
    | T
    | {
        title?: T
        description?: T
        image?: T
      }
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T
  slug?: T
  clientRef?: T
  client?: T
  industry?: T
  challenge?: T
  outcome?: T
  metrics?:
    | T
    | {
        label?: T
        value?: T
        id?: T
      }
  services?: T
  relatedSolutions?: T
  technologies?: T
  featuredImage?: T
  meta?:
    | T
    | {
        title?: T
        description?: T
        image?: T
      }
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T
  slug?: T
  insightType?: T
  excerpt?: T
  content?: T
  cover?: T
  author?: T
  categories?: T
  tags?: T
  relatedServices?: T
  relatedSolutions?: T
  relatedIndustries?: T
  readingTime?: T
  featured?: T
  publishedAt?: T
  meta?:
    | T
    | {
        title?: T
        description?: T
        image?: T
      }
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research_select".
 */
export interface ResearchSelect<T extends boolean = true> {
  title?: T
  slug?: T
  excerpt?: T
  content?: T
  cover?: T
  authors?: T
  relatedServices?: T
  relatedSolutions?: T
  relatedIndustries?: T
  featured?: T
  publishedAt?: T
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T
  slug?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  title?: T
  slug?: T
  description?: T
  order?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T
  role?: T
  bio?: T
  avatar?: T
  linkedIn?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers_select".
 */
export interface CareersSelect<T extends boolean = true> {
  title?: T
  slug?: T
  departmentRef?: T
  department?: T
  office?: T
  location?: T
  type?: T
  workMode?: T
  experienceRequired?: T
  openings?: T
  postedAt?: T
  applicationDeadline?: T
  aboutRole?: T
  description?: T
  responsibilities?:
    | T
    | {
        item?: T
        id?: T
      }
  requiredSkills?:
    | T
    | {
        item?: T
        id?: T
      }
  preferredSkills?:
    | T
    | {
        item?: T
        id?: T
      }
  qualifications?: T
  benefits?:
    | T
    | {
        item?: T
        id?: T
      }
  requirements?: T
  relatedServices?: T
  relatedSolutions?: T
  relatedIndustries?: T
  active?: T
  meta?:
    | T
    | {
        title?: T
        description?: T
        image?: T
      }
  updatedAt?: T
  createdAt?: T
  _status?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments_select".
 */
export interface DepartmentsSelect<T extends boolean = true> {
  title?: T
  slug?: T
  description?: T
  order?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "interviews_select".
 */
export interface InterviewsSelect<T extends boolean = true> {
  title?: T
  application?: T
  job?: T
  interviewers?: T
  scheduledAt?: T
  mode?: T
  meetingLink?: T
  outcome?: T
  notes?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications_select".
 */
export interface JobApplicationsSelect<T extends boolean = true> {
  applicationId?: T
  career?: T
  name?: T
  firstName?: T
  lastName?: T
  email?: T
  phone?: T
  country?: T
  city?: T
  linkedin?: T
  portfolio?: T
  currentCompany?: T
  currentDesignation?: T
  totalExperience?: T
  relevantExperience?: T
  currentSalary?: T
  expectedSalary?: T
  noticePeriod?: T
  workAuthorization?: T
  education?:
    | T
    | {
        highestQualification?: T
        university?: T
        graduationYear?: T
      }
  skills?:
    | T
    | {
        item?: T
        id?: T
      }
  resume?: T
  coverLetter?: T
  whyJoin?: T
  willingToRelocate?: T
  earliestJoinDate?: T
  healthcareExperience?: T
  consent?: T
  status?: T
  recruiterNotes?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T
  authorName?: T
  authorRole?: T
  company?: T
  logo?: T
  featured?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T
  role?: T
  department?: T
  bio?: T
  photo?: T
  order?: T
  linkedIn?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T
  logo?: T
  url?: T
  featured?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T
  answer?: T
  group?: T
  relatedServices?: T
  relatedPages?: T
  order?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies_select".
 */
export interface TechnologiesSelect<T extends boolean = true> {
  title?: T
  slug?: T
  category?: T
  logo?: T
  description?: T
  featured?: T
  order?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  type?: T
  data?: T
  status?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T
  company?: T
  email?: T
  phone?: T
  subject?: T
  message?: T
  intent?: T
  jobTitle?: T
  country?: T
  status?: T
  assignee?: T
  meetingAt?: T
  nextFollowUp?: T
  dealValue?: T
  activityNotes?:
    | T
    | {
        note?: T
        at?: T
        id?: T
      }
  notes?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T
  status?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-campaigns_select".
 */
export interface NewsletterCampaignsSelect<T extends boolean = true> {
  title?: T
  subject?: T
  sentAt?: T
  audienceFilter?: T
  notes?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "downloads_select".
 */
export interface DownloadsSelect<T extends boolean = true> {
  title?: T
  slug?: T
  description?: T
  file?: T
  relatedBlog?: T
  relatedResearch?: T
  gated?: T
  downloadCount?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-logs_select".
 */
export interface ActivityLogsSelect<T extends boolean = true> {
  summary?: T
  action?: T
  collectionSlug?: T
  documentId?: T
  actor?: T
  meta?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  title?: T
  body?: T
  type?: T
  href?: T
  user?: T
  read?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-events_select".
 */
export interface AnalyticsEventsSelect<T extends boolean = true> {
  type?: T
  path?: T
  referrer?: T
  meta?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T
  priority?: T
  doc?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T
  data?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T
  globalSlug?: T
  user?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T
  key?: T
  value?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T
  batch?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * Brand identity, theme tokens, and legacy social links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string
  siteName: string
  tagline?: string | null
  footerCopyright?: string | null
  logo?: (string | null) | Media
  logoDark?: (string | null) | Media
  favicon?: (string | null) | Media
  theme?: {
    primaryColor?: string | null
    secondaryColor?: string | null
    accentColor?: string | null
  }
  /**
   * Prefer Social Media global for new projects.
   */
  social?: {
    linkedin?: string | null
    twitter?: string | null
    github?: string | null
    youtube?: string | null
  }
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * Primary desktop menu, header CTA, and sticky header behavior.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: string
  /**
   * Drag to reorder. Mega selects open the matching mega panel.
   */
  primaryLinks?:
    | {
        label: string
        href: string
        mega?:
          | (
              | 'none'
              | 'about'
              | 'company'
              | 'solutions'
              | 'services'
              | 'industries'
              | 'insights'
              | 'research'
            )
          | null
        id?: string | null
      }[]
    | null
  cta?: {
    label?: string | null
    href?: string | null
    style?: ('primary' | 'secondary' | 'ghost') | null
    openInNewTab?: boolean | null
  }
  /**
   * Prefer CTA group above. Kept for compatibility.
   */
  ctaLabel?: string | null
  ctaHref?: string | null
  stickyHeader?: boolean | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * Footer link columns, newsletter toggle, and copyright.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string
  /**
   * Each column is a group (Company, Services, …) with nested links.
   */
  columns?:
    | {
        title: string
        links?:
          | {
              label: string
              href: string
              id?: string | null
            }[]
          | null
        id?: string | null
      }[]
    | null
  showNewsletter?: boolean | null
  copyright?: string | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * Public contact channels shown on the Contact page and site footer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-details".
 */
export interface ContactDetail {
  id: string
  email?: string | null
  phone?: string | null
  whatsapp?: string | null
  /**
   * e.g. Mon–Fri 9:00–18:00 IST
   */
  hours?: string | null
  /**
   * Google Maps embed src URL (preferred over raw HTML)
   */
  mapEmbedUrl?: string | null
  /**
   * Paste Google Maps iframe embed HTML if URL is unavailable
   */
  mapEmbed?: string | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * Physical offices shown on Contact and About pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "office-locations".
 */
export interface OfficeLocation {
  id: string
  /**
   * Each office appears as a card on the public Contact page.
   */
  locations?:
    | {
        name: string
        city: string
        country: string
        address: string
        hours?: string | null
        id?: string | null
      }[]
    | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * Default meta, Open Graph, and social sharing for public pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults".
 */
export interface SeoDefault {
  id: string
  /**
   * Use %s as page title placeholder (e.g. "%s | Xelarvis")
   */
  titleTemplate?: string | null
  defaultDescription?: string | null
  ogImage?: (string | null) | Media
  twitterHandle?: string | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-media".
 */
export interface SocialMedia {
  id: string
  linkedin?: string | null
  instagram?: string | null
  facebook?: string | null
  youtube?: string | null
  twitter?: string | null
  github?: string | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics".
 */
export interface Analytics {
  id: string
  googleAnalyticsId?: string | null
  googleTagManagerId?: string | null
  metaPixelId?: string | null
  linkedinPixelId?: string | null
  microsoftClarityId?: string | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * Site-wide announcement strip with optional CTA and expiry.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcement-bar".
 */
export interface AnnouncementBar {
  id: string
  enabled?: boolean | null
  expiresAt?: string | null
  message?: string | null
  ctaLabel?: string | null
  ctaLink?: string | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * Consent banner copy, accept label, and privacy policy link.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-banner".
 */
export interface CookieBanner {
  id: string
  enabled?: boolean | null
  message?: string | null
  policyHref?: string | null
  acceptLabel?: string | null
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T
  tagline?: T
  footerCopyright?: T
  logo?: T
  logoDark?: T
  favicon?: T
  theme?:
    | T
    | {
        primaryColor?: T
        secondaryColor?: T
        accentColor?: T
      }
  social?:
    | T
    | {
        linkedin?: T
        twitter?: T
        github?: T
        youtube?: T
      }
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  primaryLinks?:
    | T
    | {
        label?: T
        href?: T
        mega?: T
        id?: T
      }
  cta?:
    | T
    | {
        label?: T
        href?: T
        style?: T
        openInNewTab?: T
      }
  ctaLabel?: T
  ctaHref?: T
  stickyHeader?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        title?: T
        links?:
          | T
          | {
              label?: T
              href?: T
              id?: T
            }
        id?: T
      }
  showNewsletter?: T
  copyright?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-details_select".
 */
export interface ContactDetailsSelect<T extends boolean = true> {
  email?: T
  phone?: T
  whatsapp?: T
  hours?: T
  mapEmbedUrl?: T
  mapEmbed?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "office-locations_select".
 */
export interface OfficeLocationsSelect<T extends boolean = true> {
  locations?:
    | T
    | {
        name?: T
        city?: T
        country?: T
        address?: T
        hours?: T
        id?: T
      }
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults_select".
 */
export interface SeoDefaultsSelect<T extends boolean = true> {
  titleTemplate?: T
  defaultDescription?: T
  ogImage?: T
  twitterHandle?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-media_select".
 */
export interface SocialMediaSelect<T extends boolean = true> {
  linkedin?: T
  instagram?: T
  facebook?: T
  youtube?: T
  twitter?: T
  github?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics_select".
 */
export interface AnalyticsSelect<T extends boolean = true> {
  googleAnalyticsId?: T
  googleTagManagerId?: T
  metaPixelId?: T
  linkedinPixelId?: T
  microsoftClarityId?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcement-bar_select".
 */
export interface AnnouncementBarSelect<T extends boolean = true> {
  enabled?: T
  expiresAt?: T
  message?: T
  ctaLabel?: T
  ctaLink?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-banner_select".
 */
export interface CookieBannerSelect<T extends boolean = true> {
  enabled?: T
  message?: T
  policyHref?: T
  acceptLabel?: T
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown
  }
  width: 'full'
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
